{% set name = "cinnabar" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenFreeEnergy/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: fa99f945e6d50c464a697a2bf6577fe9ed5a11696ec1de67b1fa6b40795b1e8f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - adjusttext
    - matplotlib-base
    - networkx
    - numpy
    - plotly
    - python
    - scikit-learn
    - seaborn

test:
  imports:
    - cinnabar
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/OpenFreeEnergy/cinnabar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Consistent presentation of free energy data

extra:
  recipe-maintainers:
    - hannahbrucemacdonald
    - glass-w
    - mikemhenry
    - ijpulidos
    - jchodera
    - IAlibay
    - richardjgowers
    - dwhswenson
