{% set name = "arsenic" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 7fe01b249ff0ae0266d51e6f603d9966c3c10dd3dfd1097b180c246bfd19c615

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - networkx
    - numpy
    - matplotlib-base
    - seaborn
    - plotly
    - python
    - scikit-learn

test:
  imports:
    - openff.arsenic
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/openforcefield/openff-arsenic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Consistent presentation of free energy data'

extra:
  recipe-maintainers:
    - hannahbrucemacdonald
    - glass-w
    - mikemhenry
    - ijpulidos
    - jchodera
