{% set name = "cinnabar" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenFreeEnergy/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: da5e6a99b4177fe43909b0e6ffddd4a2827c1db0dfb10e12e14018d9118f2ab3

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - networkx
    - numpy
    - matplotlib-base
    - seaborn
    - plotly
    - python
    - scikit-learn

test:
  imports:
    - cinnabar
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/OpenFreeEnergy/cinnabar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Consistent presentation of free energy data'

extra:
  recipe-maintainers:
    - hannahbrucemacdonald
    - glass-w
    - mikemhenry
    - ijpulidos
    - jchodera
    - IAlibay
    - richardjgowers
    - dwhswenson
